name: agrosmart_flutter
description: "AgroSmart is a cross-platform farm management software designed to help livestock farmers manage their operations efficiently. This repository contains the frontend application built with Flutter, which connects to the backend API (Spring Boot with Kotlin)."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Estado y Arquitectura
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navegación
  go_router: ^12.1.3

  # HTTP y Networking
  dio: ^5.3.4
  json_annotation: ^4.8.1

  # UI y Gráficos
  fl_chart: ^0.65.0
  cached_network_image: ^3.3.0

  # Utilidades
  intl: ^0.18.1
  uuid: ^4.2.2
  path_provider: ^2.0.0
  open_file_plus: ^3.0.0
  permission_handler: ^10.0.0
  flutter_svg: ^2.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Manejo de archivos e imágenes
  image_picker: ^1.0.4
  #file_picker: ^6.1.1

  # icons
  cupertino_icons: ^1.0.8
  blobs: 2.0.0
  shimmer: ^3.0.0
  fading_edge_scrollview: ^4.1.1

  # scroll

dev_dependencies:

  flutter_test:
    sdk: flutter

    # Generación de código
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

  flutter_lints: ^5.0.0

  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/app_logo.png"
  adaptive_icon_background: "#003814"
  adaptive_icon_foreground: "assets/logos/app_logo.png"

  web:
    generate: true
    image_path: "assets/logos/app_logo.png"
    background_color: "#003814"
    theme_color: "#003814"
  windows:
    generate: true
    image_path: "assets/logos/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logos/app_logo.png"

flutter:
  uses-material-design: true

  # -------------------- local assets -------------------- #
  assets:
    - assets/logos/
    - assets/images/animations/
    - assets/images/content/
    - assets/images/backgrounds/
    - assets/icons/

  # -------------------- local fonts --------------------- #

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets\fonts\inter\Inter-Light.ttf
          weight: 300
        - asset: assets\fonts\inter\Inter-Bold.ttf
          weight: 800
        - asset: assets\fonts\inter\Inter-Italic.ttf
          style: italic
